### ISSUE TITLE
Minimum node version--5 (package.json) or 7 (readme)?

### ISSUE THREAD

**Issue by IBwWG** [eddyystop/feathers-starter-react-redux-login-roles#10]
Does this mean it would run on 6, maybe better for production environments anyway?

**Comment by eddyystop** [comment]
Changed both to node 6.9.0 (version in LTS) and npm 3.10.8 as. if you are starting a new project, why would you use anything else.

React runs **much** faster in production mode than in development mode.
Based on how long Travis tests take to complete, node 6 runs significantly faster than 4.

In 0.3.1 when its pushed.

**Comment by IBwWG** [comment]
It's not that I would use 5, but I had just installed 6 and then read the docs and installed 7, when I could have stayed with 6.  :)  Anyway thanks for clarifying, looking forward to the next release.

**Comment by eddyystop** [comment]
Odd numbered Node versions are allowed to introduce breaking changes, even ones are not. So you use 7 to prepare for  8, which will be in Long Term Support. But its best not to use off versions for production.

I assume you know of `nvm-windows`. It makes changing versions easy. (I use `nvm` on Ubuntu and `nvm-windows` is supposed to work the same way.)

**Comment by IBwWG** [comment]
Exactly.  :)

Yes, but I had trouble running it out of the box.  Seems to be a theme with me sometimes!  nvm worked great for me on Linux Mint though.
