### ISSUE TITLE
build:devserver and start:devserver fail to launch on windows after upgrading to 0.3.0

### ISSUE THREAD

**Issue by IBwWG** [eddyystop/feathers-starter-react-redux-login-roles#11]
This is separate from trying to run production, which is still broken, but was before 0.3.0 as well: https://github.com/eddyystop/feathers-starter-react-redux-login-roles/issues/7#issuecomment-269819551

`npm run build:devserver` *had* been working before 0.3.0 (whatever was current yesterday morning worked.)  Now it gives this:

```dos
> NODE_ENV=devserver webpack-dev-server --config webpack.devserver.config.js --c
ontent-base public/dist/ | grep -v  "\[built\]"

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:devserver"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! feathers-starter-react-redux-login-roles@0.3.0 build:devserver: `NODE_E
NV=devserver webpack-dev-server --config webpack.devserver.config.js --content-b
ase public/dist/ | grep -v  "\[built\]"`
npm ERR! Exit status 255
```

I get similar results trying to run `npm run start:devserver`, which also had been working prior to 0.3.0.

**Comment by eddyystop** [comment]
`npm run win:build:devserver` should be used on Windows.

README and FAQ updated in 0.3.1.
