### ISSUE TITLE
HTTPS warning

### ISSUE THREAD

**Issue by IBwWG** [eddyystop/feathers-starter-react-redux-login-roles#13]
In production, posting to `/users` to create a new user gives this warning in the node console:

```
WARN: Request isn't served through HTTPS: JWT in the cookie is exposed.
If you are behind a proxy (e.g. NGINX) you can:
- trust it: http://expressjs.com/en/guide/behind-proxies.html
- set cookie.secure false
```

**Comment by eddyystop** [comment]
This is from `feathers-authenticate` and I'm not familiar with that setup. I'm sorry you'll have to take this issue there too.

**Comment by IBwWG** [comment]
Well, what I mean is that, if the warning is legit, the starter should probably serve via HTTPS.  (Or maybe there could be directions somewhere for adding that for oneself.)  I say this only because of the "production ready" advertisement.  :)

**Comment by eddyystop** [comment]
Understood. Added an issue.
