### ISSUE TITLE
Users schema

### ISSUE THREAD

**Issue by janpoltan** [eddyystop/feathers-starter-react-redux-login-roles#24]
I was migrating the users service to use mysql as backend db.

```
const sequelize = new Sequelize('test_db', 'root', 'root', {
    host: 'localhost', dialect: 'mysql'
  })

  const User = sequelize.define('users', {
    username: {
      type: Sequelize.STRING,
      allowNull: false
    },
    email: {
      type: Sequelize.STRING,
      allowNull: false
    },
    password: {
      type: Sequelize.STRING,
      allowNull: false
    },
    roles: {
      type: Sequelize.STRING,
      allowNull: true
    },
    isVerified: {
      type: Sequelize.BOOLEAN,
      allowNull: true
    },
    verifyExpires: {
      type: Sequelize.STRING,
      allowNull: true
    },
    verifyToken: {
      type: Sequelize.STRING,
      allowNull: true
    }
  })

  const options = {
    Model: User,
    paginate: {
      default: 5,
      max: 25
    }
  }


  // Initialize our service with any options it requires
  app.use('/users', service(options));

  // Get our initialize service to that we can bind hooks
  const userService = app.service('/users');

  // Set up our before hooks
  userService.before(hooks.before(app));

  // Set up our after hooks
  userService.after(hooks.after);
```

It saves properly, but whenever i login a user an error occured

`Uncaught TypeError: Cannot read property 'isVerified' of undefined
`

**Comment by eddyystop** [comment]
The repo expects 5 properties to be defined in the user model, and 'isVerfied' is one of them. The docs identify the 5 properties. Please add them and try again.

**Comment by janpoltan** [comment]
Yes i have defined the isVerified in the user model
...
`isVerified: {
      type: Sequelize.BOOLEAN,
      allowNull: true
    },`

There's an error on verifying the token
`11:28:10 - info: Agent connected deviceId=nG29FUDbohndtGMDOallo3lKOK6IxY, tags=client
(node:1358) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): GeneralError: The 'restrictToOwner' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.`

Used knex instead sequelize but still same error. Can you point me the documents for the users schema?

**Comment by eddyystop** [comment]
Its in the JSDoc:

* (A) THE SERVICE
* The service creates and maintains the following properties in the user item:
*    isVerified        if the user's email addr has been verified (boolean)
*    verifyToken       the 30-char token generated for email addr
verification (string)
*    verifyTokenShort  the 6-digit token generated for email addr
verification (string)
*    verifyExpires     when the email addr token expire (Date)
*    resetToken        the 30-char token generated for forgotten
password reset (string)
*    resetTokenShort   the 6-digit token generated for forgotten
password reset (string)
*    resetExpires      when the forgotten password token expire (Date)

Define them all in the model, and create default values when you create the
user. isVerified = false, rest are null or some past Date.

The repo, as is, only creates the fields as needed.

**Comment by janpoltan** [comment]
Added the required fields in the users model/schema and the users are able to signup but cannot verified.

On the verification page the error messages was:
'VERIFYRESET: TIMEOUT OF 5000MS EXCEEDED CALLING VERIFYINGRESET:/ACTION/:VALUE::CREATE

I am using mysql on knex service.

**Comment by eddyystop** [comment]
I assume you got that message on the client. It means that the verifyreset call failed without returning an error. I'm assuming the DB swallowed the call.

I'm not familiar (anymore) with SQL DBs. Let me ask around.

**Comment by ljubic** [comment]
@eddyystop @janpoltan 

I cloned the project on my machine & switched the database from NeDB to SQL (postgre) using sequelize as well. However, when the User signs in, the action **SERVICES_AUTHENTICATION_AUTHENTICATE_FULFILLED** is logged using loggerBasic as finished and the **token** is **stored** locally, but user doesn't get logged in. The state of the auth is loading.

Only thing I changed from your repo is the User Model, which looks like this:
`const User = sequelize.define('user', {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true
        },
        name: Sequelize.STRING,
        email: Sequelize.STRING,
        username: Sequelize.STRING,
        password: Sequelize.STRING,
        verifyToken: Sequelize.STRING,
        roles: Sequelize.STRING,
        isVerified: Sequelize.BOOLEAN,
        verifyExpires: Sequelize.DATE,
        resetToken: Sequelize.STRING,
        resetExpires: Sequelize.DATE,
    });
`
Should I change something else in code? Did I miss some field in the User model (for e.g. is there maybe a field for token) ?

Thanks!

**Comment by ljubic** [comment]
Setting **idField** option to **id** in:
` .configure(authentication({idField: 'id'}))`
solved the issue.

**Comment by ljubic** [comment]
Setting idField issue solved the problem, but now I realised that verification is not working. Sequelize logs give me following error in servers terminal output:
```
...
23:26:17 - info: Server listening on port 3030 tags=server
(node:16148) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
23:26:17 - info: Connection has been established successfully.
23:30:46 - info: GET /user/verify/a7380e6eef2fecbe80467bf2dd5f5a (304) 11.854

23:30:46 - info: GET /App.css (304) 10.350

23:30:47 - info: Agent connected deviceId=mxfPBFmMB98uJ6C4h6I02aQlkTEloi, tags=client
(node:16148) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): GeneralError: No record found for id 'undefined'
(node:16148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

@eddyystop do you maybe know what could cause the issue?

**Comment by eddyystop** [comment]
`feathers-service-verify-reset` used in this repo was moved into feathers as `feathers-authentication-management` so https://github.com/feathersjs/feathers-authentication-management/issues/44 is relevant.

**Comment by ljubic** [comment]
Solved. The problem was that this repo use an old version of feathers-service-verify-reset, which has ID field hardcoded as user._id. Hope it helps someone 😄

**Comment by eddyystop** [comment]
Good job & sorry for the issue.

Where is _id hardcoded?

**Comment by ljubic** [comment]
In update functions inside this file:
https://github.com/eddyystop/feathers-service-verify-reset/blob/ae1f1dda0aef5785343286be54378d3ed4526b3e/src/index.js

v0.4.7

**Comment by wulabs** [comment]
@ljubic How did you fix the user._id problem? I have the exact same problem
