### ISSUE TITLE
devDependencies overlap with dependencies

### ISSUE THREAD

**Issue by stretchkennedy** [eddyystop/feathers-starter-react-redux-login-roles#25]
In package.json, some packages are listed in both `depedencies` and `devDependencies`. Confusingly, they seem to list different versions.

**Comment by eddyystop** [comment]
Thanks for catching that. I'd use the newer version.

I hope to do a major refresh of the repo when the Feathers Auk release
comes out and stablizes.

**Comment by eddyystop** [comment]
https://github.com/eddyystop/feathers-starter-react-redux-login-roles/issues/26
