### ISSUE TITLE
npm run win:start  - don`t work on windows

### ISSUE THREAD

**Issue by kokikillara** [eddyystop/feathers-starter-react-redux-login-roles#31]
ENOENT: no such file or directory, open 'D:\...\feathers-starter-react-redux-login-roles\logs\server.log'
Error: ENOENT: no such file or directory, open 'D:\...\feathers-starter-react-redux-login-roles\logs\server.log'
    at Error (native)

**Comment by eddyystop** [comment]
Could you try again after making sure empty log files exist.

**Comment by kokikillara** [comment]
Please add  logs/server.log in the repo , because handleUncaughtException trow error when they are missing.

**Comment by kokikillara** [comment]
I am using Windows 10 x64

**Comment by newaeonweb** [comment]
Same issue on Mac OS X 10.11.5 El Captain

**Comment by eddyystop** [comment]
Thanks for the info. This repo is scheduled for a rewrite and they will be addressed then.
