### ISSUE TITLE
Getting 'host is not recognized' on windows 7

### ISSUE THREAD

**Issue by RupeshLingampalli** [eddyystop/feathers-starter-react-redux-login-roles#32]
Trying to execute protractor scripts on windows 7 but getting ''HOST' is not recognized as an internal or external command' error. I am sure I am missing some environment variable but not sure what is it. Please suggest. Thanks

**Comment by eddyystop** [comment]
Are you referring to Protractor which is an Angular testing tool? If so, I am confused. This repo uses React/Redux not Angular.

**Comment by RupeshLingampalli** [comment]
Thanks, Can you help me with link for Angular repo?

**Comment by eddyystop** [comment]
Sorry but I don't use Angular.
