### ISSUE TITLE
Utilize feathers-authentication-management ?

### ISSUE THREAD

**Issue by leob** [eddyystop/feathers-starter-react-redux-login-roles#34]
@eddyystop Thanks for this cool project, I've looked at a number of "starters" but this project seems to strike the right balance (regarding the amount of features). The Redux integration looks attractive as well as a bunch of other features.

However I saw that there is now an official "feathers-authentication-management" plugin (https://docs.feathersjs.com/api/authentication/local-management.html) which is doing a lot of the same things which your starter is doing.

Would it make sense to replace some code with calls to that plugin (I suppose the plugin doesn't do UI so you would still need that) and how difficult would that be? I might have a shot at it.

**Comment by eddyystop** [comment]
`feathers-authentication-management` originally came from this project and
was subsequently enhanced.

I would recommend you update this repo using that, and a PR would be
welcome.

**Comment by leob** [comment]
I see, that's what I guessed already, so this shouldn't be too hard. Would it be helpful to add some unit tests to aid in making sure that I'm not breaking stuff while doing these changes?

**Comment by eddyystop** [comment]
Well the repo doesn't have any tests, so why test just this?

I suggest you make the changes, use them in your project and then push the PR. There is no hurry.

**Comment by leob** [comment]
While I'm at it I might as well replace the feathers-reduxify-services dependency by feathers-redux (the feathers-reduxify-services README says that feathers-redux is backwards compatible) ...

**Comment by leob** [comment]
Started working on it now, this is a bit less simple than it looked. First thing is I need to upgrade feathers-authentication to version 1.x because feathers-authentication-management depends on that (via feathers-authentication-local).

Migration of feathers-authentication to 1.x:

https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md

**Comment by leob** [comment]
I'm probably not going to be able to spend more time on this issue, closing it for now.
