### ISSUE TITLE
I do not see forgot password anywhere in the app. 

### ISSUE THREAD

**Issue by jpca999** [eddyystop/feathers-starter-react-redux-login-roles#36]
![image](https://user-images.githubusercontent.com/1026325/31203599-d429d0be-a935-11e7-89ca-43a81007bd14.png)

**Comment by eddyystop** [comment]
https://github.com/eddyystop/feathers-starter-react-redux-login-roles/tree/master/client/screens/Users

The screen is there. You access it on the sign in screen, which is traditional.

**Comment by jpca999** [comment]
your right, i didnt look for it enough.
