### ISSUE TITLE
postmarkapp setup

### ISSUE THREAD

**Issue by jpca999** [eddyystop/feathers-starter-react-redux-login-roles#37]
In order to start using yoru  app/ code, I assume that we need to postmarkapp, which is a pain in the neck to setup, ,why dont have used other transactional email like sendgrid which is much easir to setup and start using your app ?

Do you think you can provide users with that option ?

2) I tried sending the email when i click the Forgot password , but i never received any email and no error message is thrown in the console.. 

![image](https://user-images.githubusercontent.com/1026325/31301952-106f9922-aacc-11e7-92ff-0bf7508172d7.png)

Here i have got the emial with Postman started working. 

![image](https://user-images.githubusercontent.com/1026325/31301974-2fe5d7a8-aacc-11e7-83bf-53d732ee9fee.png)

**Comment by eddyystop** [comment]
Different people like using different email for sifferent reasons. I believe the repo is already opiniated enough.
