### ISSUE TITLE
how can i replace the existing email service with nodemailer/ gmail ?

### ISSUE THREAD

**Issue by jpca999** [eddyystop/feathers-starter-react-redux-login-roles#41]

**Comment by eddyystop** [comment]
There is no existing email service in the repo, the `notifier` function parameter calls the email service you provide.

**Comment by jpca999** [comment]
K, I’ll look into it.  

(my another issue)- Did you try generating a service ,  this app doesn’t like it and it stops working.

**Comment by eddyystop** [comment]
Did you use feathers-cli? If so, this repo pre-dates it. You have to add
services by hand.
