### ISSUE TITLE
Typescript upgrade

### ISSUE THREAD

**Issue by brewsoftware** [eddyystop/feathers-starter-react-redux-login-roles#5]
Hey, just a question. 

Do you think you would be interested in upgrading this to Typescript?

I'm kind of a stickler for TS and would love to see this example at least follow the TS pattern where it can. 

Cheers,
Jason - BrewSoftware

**Comment by eddyystop** [comment]
Thanks for asking.

This is a starter package for where I work. TS isn't used here as we want to avoid a build step for the server code.

You can always fork it if you have to, but then be aware:

`feathers-hooks-common` went from this repo to feathers core. `feathers-services-verify-reset` is moving into core as `feathers-authentication-management` having been refactored and getting new features. `feathers-reduxify-services` might one day move into core, though its arguable whether its within feathers stated purpose.

Interested people might push TS defns for these as they have for other parts of feathers.

**Comment by brewsoftware** [comment]
No problem, thanks for the context. I think we can leave it out.

Yer I've just jumped on feathers as an experiment so not that familiar with the ecosystem yet. Redux stuff doesn't belong in the core but the rest does.

Thanks for the example. If it think of anything else I will let you know.

Cheers,
Jason
