### ISSUE TITLE
Admin option shown in menu to non-admin user

### ISSUE THREAD

**Issue by IBwWG** [eddyystop/feathers-starter-react-redux-login-roles#8]
When logged in as a user with no roles, if you go to User Profile, the menu then has "Change roles (admin)".  Clicking it immediately logs you out, but it shouldn't be visible in the first place.

**Comment by eddyystop** [comment]
Thanks for mentioning this. You are correct.

I chose not to implement better permissions on menus as that leads into a whole other topic which I felt was outside the scope of the repo.

I may revisit the topic when the repo is eventually upgraded to the Auk version of Feathers. But that would likely require first writing a repo which handles menu permissions.

**Comment by IBwWG** [comment]
OK fair enough.  :)  Thanks for your response.
